# -*- coding: utf-8 -*-
"""SkinTone Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOsONlOUWw_Q8CvD1DZkKzrc3GIrE29f
"""

!pip install Pillow

from google.colab import drive
drive.mount('/content/drive')

import os
import math
from PIL import Image
from typing import Union, Tuple

# 画像から平均RGB値を取り出す
def calculate_average_rgb(image_path: str) -> Union[Tuple[int, int, int], None]:
    if not os.path.exists(image_path):
        print(f"❌ エラー: ファイル '{image_path}' が見つかりません。パスを確認してください。")
        return None
    try:
        img = Image.open(image_path)

        max_size = 100 # 処理速度を上げるため、画像サイズを調整
        if img.width > max_size or img.height > max_size:
            img = img.resize((max_size, int(img.height * max_size / img.width)))

        img = img.convert("RGB") # 色表現をRGB形式に統一

        r_sum, g_sum, b_sum = map(sum, zip(*img.getdata()))
        total_pixels = img.width * img.height # ピクセル総数

        avg_r = int(round(r_sum / total_pixels))
        avg_g = int(round(g_sum / total_pixels))
        avg_b = int(round(b_sum / total_pixels))

        return (avg_r, avg_g, avg_b) # RGB平均値

    except Exception as e:
        print(f"❌ 画像処理中にエラーが発生しました: {e}")
        return None

def rgb_to_hsb(r_int: int, g_int: int, b_int: int) -> Tuple[int, int, int]: # RGB値を受け取り、HSB（色相、彩度、明度）を返す
  # 0 ~ 1に正規化
  r = r_int / 255.0
  g = g_int / 255.0
  b = b_int / 255.0

  v = max(r, g, b) # 明度
  c = v - min(r, g, b) # 色の濃さ
  s = c / v if v != 0 else 0 # 彩度

  if c == 0:
    h = 0
  elif v == r:
    h = (g - b) / c
  elif v == g:
    h = (b - r) / c + 2
  else:
    h = (r - g) / c + 4

  h *= 60 # 0 ~ 360°に変換
  if h < 0: # 正の値にする
    h += 360

  return int(round(h)), int(round(s * 100)), int(round(v * 100))

def analyze_skin_tone(h: int, s: int, v: int) -> str: # HSB値を受け取る

    # イエベ判定
    if 10 <= h <= 60:
      base_tone = "🟡 イエベ（Warm）"
      if v >= 70 and s >= 30:
          return f"{base_tone} / 🌸 春 (Spring)"
      else:
          return f"{base_tone} / 🍁 秋 (Autumn)"

    # ブルベ判定
    elif 200 <= h <= 280:
      base_tone = "🔵 ブルベ（Cool）"
      if v >= 65 and s < 30:
          return f"{base_tone} / 🏖️ 夏 (Summer)"
      else:
          return f"{base_tone} / ❄️ 冬 (Winter)"

    # ニュートラル判定
    else:
      return "ニュートラル (判定不能)"

def main_cli():
    """SkinTone Analyzer のメインの対話型CLIインターフェース"""
    print("--------------------------------------------------")
    print("✨ SkinTone Analyzer CLI ✨")
    print("  色分析を開始します。")
    print("  終了する場合は 'end' を入力してください。")
    print("--------------------------------------------------")

    # Google Driveのベースパスを設定
    drive_base_path = '/content/drive/MyDrive/'

    while True:
        # ユーザーからの入力受付
        input_path = input(f"\n画像パスを入力 (例: sample01.jpg): ")

        if input_path.lower() in ['end']:
            print("👋 分析を終了します。")
            break

        # フルパスに結合
        full_path = os.path.join(drive_base_path, input_path)

        # 1. RGB計算
        avg_color = calculate_average_rgb(full_path)

        if avg_color is None:
            continue # エラー処理は関数内で行われているため続行

        r, g, b = avg_color

        # 2. HSB計算
        h, s, v = rgb_to_hsb(r, g, b)

        # 3. トーン判定
        tone_result = analyze_skin_tone(h, s, v)

        # 4. 結果の出力（2桁の16進数）
        hex_color = f"#{r:02x}{g:02x}{b:02x}".upper()

        print("\n--- [ 分析結果 ] -----------------------------------")
        print(f"  ファイル: {input_path}")
        print(f"  平均RGB: ({r}, {g}, {b}) / HEX: {hex_color}")
        print(f"  色相: {h}°/ 彩度: {s}% / 明度: {v}%")
        print("----------------------------------------------------")
        print(f"  🎯 総合判定: {tone_result}")
        print("----------------------------------------------------")

# メイン処理の開始
if __name__ == '__main__':
    main_cli()

